### PR TITLE
WIP - starting point for UK brand styles

### PR DESCRIPTION
**Pull request by gilacost**
This is a **WIP**.
It is a **spike** to understand how can we internationalise the different components of the brand, in this case slightly change the look and feel of the UK site.

# Gif

### CODE REVIEW

**Comment by alessiosantangelo** [comment]
Hi @gilacost, just got here by chance. 
Pyxis-npm is designed to be easily overridden by client customizations. 

So the right path for defining your own colors, fonts, and every kind of customization in general should be extend the configuration map of the needed entities. 

For example, if you want to define a custom color for your own application you should do: 

```
// In your file "prima-uk-variables.scss"

// This should put in scope the $colors variable map.
@import "src/scss/01_base/variables/_colors.scss";

// Define your own customizations by maintaining the same keys you find in $colors map.
$ukColors: ( 
  brand: (
     light: #ffffff,
     base: #000000,
     dark: #f0f0f0
);

// Merge and re-assign your customizations in $colors map.
$colors: map-merge($colors, $ukColors);

// Now you can use it like this

.my-rule {
   color: color(brand, light); // #ffffff
}

```

**Comment by gilacost** [comment]
Sorry, @alessiosantangelo,  my first impression( second week at prima uk) was that we were going to use pyxis as a shared styles repo. I submitted this in order to have something similar to domus flow but with a slightly different look and feel, when I worked on the quote confirmation page. This is not needed anymore as far as I am concerned so it can be closed. I know this was a dirty solution but at the time it worked 😉

**Comment by alessiosantangelo** [comment]
Don't worry, thank you ;)

**Comment by gilacost** [comment]
You are very welcome :wink:

**Pull request closed without merging**
